### PR TITLE
Fix for https://github.com/JeffDarchuk/EPExpressTab/issues/3

### PR DESCRIPTION
**Pull request by andresvillenas**
It also included some clean-up for the Initialize class.

### CODE REVIEW

**Comment by andresvillenas** [comment]
I just noticed that I used the format document command which fixed some blank spaces in the class. Please, let me know if that is a problem.

**Comment by JeffDarchuk** [comment]
thanks for the PR, i'm not a stickler about the formatting i don't really mind, but if you could direct me to the lines that you changes beyond just the formatting, that would be super helpful for the review process.

**Comment by andresvillenas** [comment]
Yes, sure. I did some changes at the lines 51 to 54, and 67 to 70. They will handle the scenario of Tab items with the same name. Also, it will stop the creation of duplicated items.

**Comment by JeffDarchuk** [comment]
good stuff, thanks!  I'll cut a minor release with this fix in it

**Comment by JeffDarchuk** [comment]
version 2.0.2 should be available shortly

**Pull request merged**
